char *idle_s_data[20][20] = {
	{CLR,CLR,CLR,YEL,YEL,YEL,YEL,CLR,CLR,CLR},
	{CLR,CLR,YEL,YEL,YEL,YEL,YEL,YEL,CLR,CLR},
	{CLR,CLR,BLK,BLK,WHT,WHT,BLK,BLK,CLR,CLR},
	{CLR,CYN,RED,RED,RED,RED,RED,RED,CYN,CLR},
	{CYN,CYN,BLU,RED,RED,RED,RED,BLU,CYN,CYN},
	{CYN,CYN,BLU,BLU,RED,RED,BLU,BLU,CYN,CYN},
	{WHT,WHT,BLU,BLU,BLU,BLU,BLU,BLU,WHT,WHT},
	{WHT,WHT,BLU,BLU,BLU,BLU,BLU,BLU,WHT,WHT},
	{CLR,CLR,BLK,BLK,CLR,CLR,BLK,BLK,CLR,CLR},
	{CLR,BLK,BLK,BLK,CLR,CLR,BLK,BLK,BLK,CLR},
};
