// HEADER GUARD

#ifndef IDLE_E_H
#define IDLE_E_H

// INCLUDES

#include "../../head/screen.h"

// DATA

char *grass_data[20][20] = {
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
	{GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN,GRN},
};

#endif
