// HEADER GUARD

#ifndef GRASS_H
#define GRASS_H

// INCLUDES

#include "../../head/screen.h"

// DATA

char *grass_data[20][20] = {
	{IGRN,IGRN, GRN,IGRN,IGRN, GRN,IGRN,IGRN,IGRN, GRN, },
	{IGRN,IGRN, GRN,IGRN,IGRN,IGRN,IGRN,IGRN, GRN,IGRN, },
	{ GRN,IGRN,IGRN,IGRN,IGRN, GRN, GRN,IGRN, GRN,IGRN, },
	{IGRN, GRN,IGRN,IGRN, GRN,IGRN,IGRN, GRN,IGRN,IGRN, },
	{IGRN, GRN,IGRN,IGRN,IGRN,IGRN,IGRN, GRN,IGRN, GRN, },
	{IGRN,IGRN,IGRN,IGRN, GRN,IGRN,IGRN,IGRN,IGRN, GRN, },
	{ GRN, GRN,IGRN, GRN,IGRN, GRN,IGRN, GRN,IGRN,IGRN, },
	{IGRN,IGRN,IGRN,IGRN,IGRN,IGRN,IGRN, GRN,IGRN, GRN, },
	{IGRN, GRN,IGRN,IGRN, GRN,IGRN,IGRN,IGRN, GRN,IGRN, },
	{IGRN, GRN,IGRN, GRN,IGRN, GRN,IGRN,IGRN, GRN,IGRN, },
};

#endif
