// HEADER GUARD

#ifndef IDLE_N_H
#define IDLE_N_H

// INCLUDES

#include "../../head/screen.h"

// DATA

 char *idle_n_data[20][20] = {
	{CLR,CLR,CLR,YEL,YEL,YEL,YEL,CLR,CLR,CLR},
	{CLR,CLR,YEL,YEL,YEL,YEL,YEL,YEL,CLR,CLR},
	{CLR,CLR,WHT,WHT,WHT,WHT,WHT,WHT,CLR,CLR},
	{CLR,CYN,RED,RED,RED,RED,RED,RED,CYN,CLR},
	{CYN,CYN,BLU,CYN,CYN,CYN,CYN,BLU,CYN,CYN},
	{CYN,CYN,BLU,BLU,BLU,BLU,BLU,BLU,CYN,CYN},
	{WHT,WHT,BLU,BLU,BLU,BLU,BLU,BLU,WHT,WHT},
	{WHT,WHT,BLU,BLU,BLU,BLU,BLU,BLU,WHT,WHT},
	{CLR,CLR,BLK,BLK,CLR,CLR,BLK,BLK,CLR,CLR},
	{CLR,BLK,BLK,BLK,CLR,CLR,BLK,BLK,BLK,CLR},
};

#endif
