// HEADER GUARD

#ifndef IDLE_E_H
#define IDLE_E_H

// INCLUDES

#include "../../head/screen.h"

// DATA

char *idle_e_data[20][20] = {
	{ CLR, CLR, CLR,IYEL,IYEL,IYEL, YEL, CLR, CLR, CLR},
	{ CLR, CLR,IYEL,IYEL, YEL, YEL, YEL, YEL, CLR, CLR},
	{ CLR, CLR,IWHT,IBLK, BLK,IWHT, WHT,IBLK, CLR, CLR},
	{ CLR,ICYN, RED,IRED,IRED, RED,IRED,IRED,ICYN, CLR},
	{ICYN, CYN,IBLU, BLU, RED, RED,IRED, RED, CYN,ICYN},
	{ CYN, CYN,IBLU, BLU, BLU,IRED, RED,IBLU, CYN, CYN},
	{IWHT,IWHT,IBLU, BLU,IBLU,IBLU, BLU,IBLU,IWHT,IWHT},
	{IWHT, WHT, BLU, BLU, BLU, BLU, BLU, BLU, WHT,IWHT},
	{ CLR, CLR,IBLK, BLK, CLR, CLR, BLK,IBLK, CLR, CLR},
	{ CLR, CLR,IBLK, BLK, BLK, CLR, BLK, BLK,IBLK, CLR},
};

#endif
