// HEADER GUARD

#ifndef IDLE_N_H
#define IDLE_N_H

// INCLUDES

#include "../../head/screen.h"

// DATA

 char *idle_n_data[20][20] = {
	{CLR, CLR, CLR,IYEL,IYEL,IYEL, YEL, CLR, CLR, CLR},
	{CLR, CLR,IYEL,IYEL, YEL, YEL, YEL, YEL, CLR, CLR},
	{CLR, CLR,IWHT, IWHT,IWHT, WHT,WHT, WHT, CLR, CLR},
	{CLR,ICYN,IRED, RED, RED,IRED, IRED,RED, ICYN, CLR},
	{ICYN,CYN,IBLU, BLU, CYN, CYN, BLU,IBLU, CYN, ICYN},
	{CYN, CYN,IBLU, BLU, BLU, BLU, BLU,IBLU, CYN, CYN},
	{IWHT,WHT,IBLU, BLU,IBLU,IBLU, BLU,IBLU, WHT,IWHT},
	{WHT, WHT, BLU, BLU, BLU, BLU, BLU, BLU, WHT, WHT},
	{CLR, CLR, BLK,IBLK, CLR, CLR,IBLK, BLK, CLR, CLR},
	{CLR, BLK, BLK,IBLK, CLR, CLR,IBLK, BLK, BLK, CLR},
};

#endif
