char *idle_e_data[20][20] = {
	{CLR,CLR,CLR,YEL,YEL,YEL,YEL,CLR,CLR,CLR},
	{CLR,CLR,YEL,YEL,YEL,YEL,YEL,YEL,CLR,CLR},
	{CLR,CLR,WHT,WHT,WHT,BLK,BLK,WHT,CLR,CLR},
	{CLR,CLR,RED,RED,RED,RED,RED,RED,CLR,CLR},
	{CLR,CLR,BLU,CYN,CYN,BLU,RED,RED,CLR,CLR},
	{CLR,CLR,BLU,CYN,CYN,BLU,BLU,RED,CLR,CLR},
	{CLR,CLR,BLU,WHT,WHT,BLU,BLU,BLU,CLR,CLR},
	{CLR,CLR,CLR,WHT,WHT,BLU,BLU,CLR,CLR,CLR},
	{CLR,CLR,CLR,CLR,BLK,BLK,CLR,CLR,CLR,CLR},
	{CLR,CLR,CLR,CLR,BLK,BLK,BLK,CLR,CLR,CLR}
};
