// HEADER GUARD

#ifndef IDLE_S_H
#define IDLE_S_H

// INCLUDES

#include "../../head/screen.h"

// DATA

char *idle_s_data[20][20] = {
	{CLR, CLR, CLR,IYEL,IYEL,IYEL, YEL, CLR, CLR, CLR},
	{CLR, CLR,IYEL,IYEL, YEL, YEL, YEL, YEL, CLR, CLR},
	{CLR, CLR,IBLK, BLK,IWHT, WHT,IBLK, BLK, CLR, CLR},
	{CLR,ICYN,RED, IRED,RED,IRED, IRED,RED, ICYN, CLR},
	{ICYN,CYN,IBLU, RED,RED,IRED, RED,IBLU, CYN, ICYN},
	{CYN, CYN,IBLU, BLU,IRED, RED, BLU,IBLU, CYN, CYN},
	{IWHT,IWHT,IBLU, BLU,IBLU,IBLU, BLU,IBLU,IWHT,IWHT},
	{IWHT,WHT, BLU, BLU, BLU, BLU, BLU, BLU, WHT,IWHT},
	{CLR, CLR,IBLK, BLK, CLR, CLR, BLK,IBLK, CLR, CLR},
	{CLR,IBLK, BLK, BLK, CLR, CLR, BLK, BLK,IBLK, CLR},
};

#endif
