// HEADER GUARD

#ifndef IDLE_W_H
#define IDLE_W_H

// INCLUDES

#include "../../head/screen.h"

// DATA

char *idle_w_data[20][20] = {
	{ CLR, CLR, CLR,IYEL,IYEL,IYEL, YEL, CLR, CLR, CLR},
	{ CLR, CLR,IYEL,IYEL, YEL, YEL, YEL, YEL, CLR, CLR},
	{ CLR, CLR, BLK,IWHT, WHT,IBLK, BLK, WHT, CLR, CLR},
	{ CLR,ICYN, RED,IRED,IRED, RED,IRED,IRED,ICYN, CLR},
	{ICYN, CYN, RED, RED,IRED, RED, BLU,IBLU, CYN,ICYN},
	{ CYN, CYN,IBLU,IRED, RED ,BLU, BLU,IBLU, CYN, CYN},
	{IWHT,IWHT,IBLU, BLU,IBLU,IBLU, BLU,IBLU,IWHT,IWHT},
	{IWHT, WHT, BLU, BLU, BLU, BLU, BLU, BLU, WHT,IWHT},
	{ CLR, CLR,IBLK, BLK, CLR, CLR,IBLK, BLK, CLR, CLR},
	{ CLR,IBLK, BLK, BLK, CLR,IBLK, BLK, BLK, CLR, CLR},
};

#endif
