// HEADER GUARD

#ifndef IDLE_W_H
#define IDLE_W_H

// INCLUDES

#include "../../head/screen.h"

// DATA

char *idle_w_data[20][20] = {
	{CLR,CLR,CLR,YEL,YEL,YEL,YEL,CLR,CLR,CLR},
	{CLR,CLR,YEL,YEL,YEL,YEL,YEL,YEL,CLR,CLR},
	{CLR,CLR,WHT,BLK,BLK,WHT,WHT,WHT,CLR,CLR},
	{CLR,CLR,RED,RED,RED,RED,RED,RED,CLR,CLR},
	{CLR,CLR,RED,RED,BLU,CYN,CYN,BLU,CLR,CLR},
	{CLR,CLR,RED,BLU,BLU,CYN,CYN,BLU,CLR,CLR},
	{CLR,CLR,BLU,BLU,BLU,WHT,WHT,BLU,CLR,CLR},
	{CLR,CLR,CLR,BLU,BLU,WHT,WHT,CLR,CLR,CLR},
	{CLR,CLR,CLR,CLR,BLK,BLK,CLR,CLR,CLR,CLR},
	{CLR,CLR,CLR,BLK,BLK,BLK,CLR,CLR,CLR,CLR},
};

#endif
